from __future__ import annotations

import importlib.util
import json
import os
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_desktop_sidecar.py"
SPEC = importlib.util.spec_from_file_location("desktop_sidecar_builder", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
builder = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(builder)
FINALIZER = ROOT / "scripts" / "finalize_desktop_bundle.py"


def test_target_triples_and_output_names_are_closed() -> None:
    assert builder.target_triple(system="Darwin", machine="arm64") == "aarch64-apple-darwin"
    assert builder.target_triple(system="Darwin", machine="x86_64") == "x86_64-apple-darwin"
    with pytest.raises(ValueError, match="unsupported"):
        builder.target_triple(system="Linux", machine="x86_64")
    with pytest.raises(ValueError, match="allowlisted"):
        builder.output_path("../../untrusted")


def test_pyinstaller_command_is_pinned_onefile_console_and_target_suffixed() -> None:
    command = builder.pyinstaller_command("aarch64-apple-darwin")

    assert command[:3] == [os.sys.executable, "-m", "PyInstaller"]
    assert {"--onefile", "--console", "--noupx", "--clean", "--noconfirm"} <= set(command)
    name = command[command.index("--name") + 1]
    assert name == "openchronicle-desktop-bridge-aarch64-apple-darwin"
    assert command[command.index("--collect-data") + 1] == "openchronicle"
    assert Path(command[-1]) == ROOT / "resources" / "desktop_bridge_entry.py"

    signed = builder.pyinstaller_command(
        "aarch64-apple-darwin", codesign_identity="Developer ID Application: Example"
    )
    identity_index = signed.index("--codesign-identity")
    assert signed[identity_index + 1] == "Developer ID Application: Example"
    with pytest.raises(ValueError, match="identity is invalid"):
        builder.pyinstaller_command("aarch64-apple-darwin", codesign_identity="x\x00y")

    assert builder.FONT_BUILDER == ROOT / "scripts" / "fetch_pdf_fonts.py"
    assert builder.FONT_BUILDER.is_file()


def test_tauri_bundle_config_uses_external_binary_basename() -> None:
    payload = json.loads(
        (ROOT / "apps/desktop/src-tauri/tauri.bundle.conf.json").read_text(encoding="utf-8")
    )

    assert payload == {
        "$schema": "https://schema.tauri.app/config/2",
        "bundle": {"externalBin": ["binaries/openchronicle-desktop-bridge"]},
    }


def test_npm_bundle_pipeline_builds_app_then_runs_finalizer() -> None:
    package = json.loads((ROOT / "apps/desktop/package.json").read_text(encoding="utf-8"))
    command = package["scripts"]["tauri:bundle"]

    assert command.startswith("npm run sidecar:build && tauri build")
    assert "--config src-tauri/tauri.bundle.conf.json --bundles app" in command
    assert command.endswith("python ../../scripts/finalize_desktop_bundle.py")
    assert FINALIZER.is_file()
    finalizer_source = FINALIZER.read_text(encoding="utf-8")
    assert "APP_STARTUP_TIMEOUT_SECONDS = 20" in finalizer_source
    assert "APP_STABILITY_SECONDS = 1" in finalizer_source


def test_tauri_manifest_permissions_cover_every_registered_command() -> None:
    tauri_root = ROOT / "apps" / "desktop" / "src-tauri"
    registered = set(
        re.findall(
            r"commands::([a-z0-9_]+),",
            (tauri_root / "src" / "lib.rs").read_text(encoding="utf-8"),
        )
    )
    manifested = set(
        re.findall(
            r'^\s+"([a-z0-9_]+)",$',
            (tauri_root / "build.rs").read_text(encoding="utf-8"),
            flags=re.MULTILINE,
        )
    )
    allowed = {
        identifier.replace("-", "_")
        for identifier in re.findall(
            r'"allow-([a-z0-9-]+)"',
            (tauri_root / "permissions" / "desktop.toml").read_text(encoding="utf-8"),
        )
    }

    assert registered == manifested == allowed
    for command in registered:
        generated = tauri_root / "permissions" / "autogenerated" / f"{command}.toml"
        assert generated.is_file(), command
        assert f'commands.allow = ["{command}"]' in generated.read_text(encoding="utf-8")
